Console.Write("Введите первое число: ");
int numberA = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите второе число: ");
int numberB = Convert.ToInt32(Console.ReadLine());
Console.Write("Введите третье число: ");
int numberС = Convert.ToInt32(Console.ReadLine());
int max = numberA;
if(numberB > max) max = numberB; 
if(numberС > max) max = numberС;
Console.Write("max = ");
Console.WriteLine(max);